(() => {
  const activities=[...(window.academicActivities||[])].sort((a,b)=>b.date.localeCompare(a.date));
  const lang=()=>localStorage.getItem('site-language')||'en';
  const text=v=>typeof v==='string'?v:(v?.[lang()]||v?.en||'');
  const el=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value)n.textContent=value;return n};
  const date=v=>new Intl.DateTimeFormat(lang()==='zh'?'zh-CN':'en',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`));
  const row=(item,index,showImage)=>{const link=el('a','activity-row');link.href=`./activity.html?id=${encodeURIComponent(item.id)}`;const num=el('span','activity-number',String(index+1).padStart(2,'0'));const body=el('div','activity-row-body');body.append(el('time','activity-date',date(item.date)),el('h3','',text(item.title)),el('p','activity-subtitle',text(item.subtitle)),el('span','activity-read-more',lang()==='zh'?'查看详情 →':'Read more →'));link.append(num,body);if(showImage){const img=document.createElement('img');img.className='activity-image';img.src=item.images[0].src;img.alt=text(item.images[0].alt);img.loading='lazy';link.prepend(img)}return link};
  const latest=document.querySelector('[data-activities="latest"]'); const renderLatest=()=>{if(latest)latest.replaceChildren(...activities.map((item,i)=>row(item,i,false)))}; renderLatest(); window.addEventListener('languagechange',renderLatest);
  const archive=document.querySelector('[data-activities="archive"]'); if(archive)archive.replaceChildren(...activities.map((item,i)=>row(item,i,true)));
  const detail=document.querySelector('[data-activities="detail"]'); if(!detail)return; const item=activities.find(x=>x.id===new URLSearchParams(location.search).get('id')); if(!item){detail.replaceChildren(el('h1','',lang()==='zh'?'活动未找到':'Activity unavailable'));return}; const header=el('header','activity-detail-header');header.append(el('time','activity-date',date(item.date)),el('h1','',text(item.title)),el('p','activity-detail-subtitle',text(item.subtitle)));const gallery=el('div','activity-gallery');item.images.forEach(photo=>{const fig=el('figure','activity-figure');const img=document.createElement('img');img.className='activity-image';img.src=photo.src;img.alt=text(photo.alt);img.loading='lazy';fig.append(img,el('figcaption','',text(photo.caption)));gallery.append(fig)});const prose=el('div','activity-prose');(item.paragraphs[lang()]||item.paragraphs.en).forEach(p=>prose.append(el('p','',p)));detail.replaceChildren(header,gallery,prose);
})();

