window.academicActivities = [
  { id: 'complex-networks-2026', date: '2026-08-21', title: { en: 'Academic Talk · 22nd National Academic Conference on Complex Networks', zh: '学术报告·第二十二届全国复杂网络学术会议' }, subtitle: { en: 'Variational Physics-Informed Ansatz for Reconstructing Hidden Interaction Networks from Steady States', zh: '基于刘维尔特征嵌入的变分神经网络拟设的开放量子多体系统稳态解算法' }, paragraphs: { en: ['I presented a study on a variational neural-network ansatz for solving steady states in open quantum many-body systems.', 'The work combines feature representations in Liouville space with variational neural-network methods to explore a new computational framework for steady-state calculations in complex open quantum systems. The presentation covered the research question, model construction, solution method, and numerical results, followed by discussion with researchers on open-system modelling and intelligent computational methods.'], zh: ['围绕“基于刘维尔特征嵌入的变分神经网络拟设的开放量子多体系统稳态解算法”作学术报告。', '该研究面向开放量子多体系统稳态求解问题，将刘维尔空间中的特征表示与变分神经网络方法相结合，探索复杂开放量子系统稳态求解的新型计算框架。报告围绕研究问题、模型构建、求解方法及相关实验结果进行了介绍，并与现场专家学者就开放量子系统建模和智能计算方法等问题进行了交流。'] }, images: [{ src: './assets/activity-2026-talk.jpg', alt: { en: 'Kaiming Luo presenting at the conference', zh: '罗恺明在会议上作报告' }, caption: { en: 'Presentation at the 22nd National Academic Conference on Complex Networks, 2026.', zh: '第二十二届全国复杂网络学术会议报告现场，2026 年。' } }, { src: './assets/activity-2026-slide.jpg', alt: { en: 'Kaiming Luo beside the presentation screen', zh: '罗恺明与报告屏幕合影' }, caption: { en: 'The presentation on a variational neural-network ansatz for open quantum many-body systems.', zh: '关于开放量子多体系统变分神经网络拟设的报告。' } }] },
  { id: 'nonlinear-symposium-2024', date: '2024-07-22', title: { en: 'Academic Talk · Shanghai International Symposium on Nonlinear Science and Applications', zh: '学术报告·上海国际非线性科学与应用研讨会' }, subtitle: { en: 'Effects of Uncommon Non-isochronicities on Remote Synchronization', zh: '非等时性差异对遥同步的影响' }, paragraphs: { en: ['At the 10th Shanghai International Symposium on Nonlinear Sciences and Applications, I presented our study on how uncommon non-isochronicities shape remote synchronization in coupled oscillator networks.', 'The presentation compared Stuart–Landau oscillators with Kuramoto–Sakaguchi phase models. It explained how the difference and sum of non-isochronicity parameters determine direct and remote synchronization thresholds, and how remote synchronization can fade and reappear as coupling increases.'], zh: ['在第十届上海国际非线性科学与应用研讨会上，围绕非等时性差异如何影响耦合振子网络中的遥同步作学术报告。 ', '报告比较了 Stuart–Landau 振子与 Kuramoto–Sakaguchi 相位模型，介绍了非等时性参数的差值与和值如何决定直接同步和遥同步的临界耦合，并讨论了遥同步随耦合增强而消退、再出现的现象。'] }, images: [{ src: './assets/activity-2024-talk-wide.jpg', alt: { en: 'Kaiming Luo giving a presentation', zh: '罗恺明作学术报告' }, caption: { en: 'Presentation on coupled oscillator dynamics.', zh: '耦合振子动力学报告现场。' } }, { src: './assets/activity-2024-talk.jpg', alt: { en: 'Kaiming Luo speaking in front of a lecture slide', zh: '罗恺明在报告现场' }, caption: { en: 'Discussing remote synchronization and higher-order phase dynamics.', zh: '介绍遥同步与高阶相位动力学。' } }, { src: './assets/activity-2024-jurgen.jpg', alt: { en: 'Kaiming Luo with Jürgen Kurths', zh: '罗恺明与 Jürgen Kurths 合影' }, caption: { en: 'With Jürgen Kurths at the symposium.', zh: '与 Jürgen Kurths 教授在会议期间合影。' } }] },
  { id: 'complex-networks-2023', date: '2023-11-04', title: { en: 'Academic Talk · 19th National Academic Conference on Complex Networks', zh: '学术报告·第十九届全国复杂网络学术会议' }, subtitle: { en: 'Effects of Uncommon Non-isochronicities on Remote Synchronization', zh: '非等时性差异对遥同步的影响' }, paragraphs: { en: ['At the 19th National Academic Conference on Complex Networks, I presented our study of remote synchronization induced by uncommon non-isochronicities in oscillator networks.', 'The talk introduced the oscillator-network model and higher-order phase reduction, highlighting the distinct roles of non-isochronicity differences for directly coupled nodes and sums for indirectly coupled leaf nodes.'], zh: ['在第十九届全国复杂网络学术会议上，围绕非等时性差异诱导的振子网络遥同步研究作学术报告。 ', '报告介绍了振子网络模型与高阶相位约化方法，重点讨论非等时性差值对直接耦合节点、非等时性和值对间接连接叶节点的不同作用。'] }, images: [{ src: './assets/activity-2023-talk.jpg', alt: { en: 'Kaiming Luo presenting on remote synchronization', zh: '罗恺明介绍遥同步' }, caption: { en: 'Presentation on remote synchronization.', zh: '遥同步研究报告现场。' } }, { src: './assets/activity-2023-slide.jpg', alt: { en: 'Kaiming Luo presenting a perturbation theory slide', zh: '罗恺明介绍摄动理论' }, caption: { en: 'Discussing perturbation theory for coupled oscillator models.', zh: '介绍耦合振子模型中的摄动理论。' } }] }
];





